apiVersion: v1
data:
    token: ENC[AES256_GCM,data:0rntlGCoSmsr6wgvOK7MM/sn/SuvPZ6fQdOV5hwfUVTUPGmwkI9bPBEnip86sEYT2I4u/ReGvYykWI9uq6M+bQ==,iv:UzgH66L1eJAHRj27hFAnTFJLl/dV3P2A4f6hIzM3eLw=,tag:hVY7WnKQjbt8EgirQk2kaQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
    namespace: demo
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/causal-cubist-428122-k3/locations/global/keyRings/sops-flux/cryptoKeys/sops-key-flux
          created_at: "2024-08-29T21:51:39Z"
          enc: CiQAaYCSd8bWCBd0U1UIsiFAxazgKGLkx5+QsSlau+wJyHSIgesSSQBshi0rwzUFBSX9mnPzxaqVJ17rY28yvpgzRpKwXwwEPoe2ZVVIKoDZ9NfxUIjWyMK7O0kaG7H8Ebqv0nwsYa6e/XVDHpunqlw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-29T21:51:40Z"
    mac: ENC[AES256_GCM,data:q4zr5IT7JjwRqdu0yb12fQzEHK9lPxBVEx6XL+fHnjdnGPiY7YRfMPWTlmcq6v6/blOrc2/rUBr0OAjEMD+9XAKW5vArejUmEpbpjjPme9Gy59MCZEQI7IfpLkXMntu9wYvOgUtFEAy4PtblPL5x9FvrZZfA+pCTu2K0XJTjhXQ=,iv:Gxi8jRIivJYPo3F81QWJ+9aDulhJ7NiMYeM4p8aAzNg=,tag:xn3b5K6uA88kK2tRDVxkNA==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.9.0
